on:
  issues:
    types:
      - labeled

jobs:
  add-symbols:
    if: github.event.label.name == 'approved'
    permissions:
      contents: write
      issues: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/mcapi-request.yml

      - run: |
          echo $SYMBOLS >> symbols.txt
        env:
          SYMBOLS: ${{ steps.issue-parser.outputs.issueparser_symbols }}

      - run: |
          python tidy_symbols.py

      - uses: stefanzweifel/git-auto-commit-action@v5
